### ISSUE TITLE
Multiple Bugs with v2021.3.5s

### ISSUE THREAD

**Issue by Cyber-Crud** [BitCrackers/AmongUsMenu#150]
After compiling on 3/22 I noticed the following bugs while playing:

1. My avatar outfit does not show. Only my mask.  Sometimes outfit glitches in and out while moving.
2. Sometimes the game does not end when the Imps leave or when there are more imps than crew. The game locks up either without imps or without crew.  Basically, whenever the threshold for winning is met, the game continues to play.  Then black screens.
3. Sabotage on Reactor and O2 both get to zero then go negative time. It does not end the game.  This happened when I pinned doors and then performed a sabotage.
4. The game will randomly crash out on a runtime error with high frequency.

**Comment by manianac** [comment]
1.  I've only duplicated this on freecam/spectating/zoom.  Do you have this bug without using those three modes?
2.  This sounds like a desync with the host, which I have experienced myself.  The host decides all the factors you've mentioned, otherwise you're a client awaiting commands.  This is an Innersloth bug, I don't think this is related to the menu.
3. Once again, desync with host.  See 2.
4. Since you were able to compile the mod, please attach a debugger while playing.  When you capture the crash, we can see what it was.

**Comment by OsOmE1** [comment]
I fixed issue nr 1 here.
[](https://github.com/BitCrackers/AmongUsMenu/commit/0d0f8ffac2c14317a2e708eb8c7e7f97c1e1653b)

**Comment by Cyber-Crud** [comment]
Using the version that OsOmE1 compiled, I have not gotten the #3 error again.  But I do get the #2 error with the game not ending correctly almost every time I play it.

**Comment by OsOmE1** [comment]
I was able to replicate the issue when getting voted out as imposter.
@Cyber-Crud does your client crash or black screen

**Comment by Cyber-Crud** [comment]
I get the black screen and I eventually have to quit, if the game ends
without properly firing off the win/lose criteria.  I get crashing more
often if I am doing teleport kills.  For example, if I am using the Player
tab and the kill button on it, to kill a player instantly wherever they
are.  The game will sometimes crash during or after this kill.
