### ISSUE TITLE
"Kill disabled while protected by Guardian Angel" Bug and add option to disable this feature

### ISSUE THREAD

**Issue by chara26** [BitCrackers/AmongUsMenu#263]
Seems that if a player is protected for once, the client will disable kill on him "permanently".

Also suggest adding a option to disable this feature (bruh i don't need it)

**Comment by v0idp** [comment]
@BitCrackers/developers  can anyone confirm that the "protectedByGuardian" field stays even if that player is not protected anymore ?

**Comment by manianac** [comment]
A few of us will have to jump in a game to test, but I can verify protectedByGuardian should be changed to flash during meetings or murder attempts.

**Comment by puscher** [comment]
can confirm that this can happen / happens sometimes. it's not always the case.

**Comment by DarkPenguin24** [comment]
can confirm that this can happen / happens sometimes. it's not always the case.

**Comment by chara26** [comment]
Found more details about the bug

The first attempt you kill an protected player(in the protected time) , the client doesn't disable kill for you and the protect toggles( L trash feature) . After that attempt. you can never kill that player again.

Bruh can you just remove or disable that feature?

**Comment by DarkPenguin24** [comment]
I did some research on this issue and have good and bad news:
First of all this Problem is defined as follows:

1. An Imposter tries to kill a Crewmate that is protected by a Guardian Angel
2. He will receive the shield animation depending on the lobby setting whether it is shown towards the imposter or not.
3. The Imposter gets half the kill cooldown
4. If he then tries to kill the same player nothing happens and he cannot kill that player unless he was shielded again and the shield ran out without a kill attempt.
5. If he tries to kill another player (not protected) the other player dies.
6. If he tries to kill another player (protected) nothing happens and he cannot kill that player unless he was shielded again and the shield ran out without a kill attempt.


The good news:
This issue has nothing to do with AUM, it also happens if no one uses AUM.

The bad news:
It is a known Bug, which was already reported on the innersloth (among us) discord.
I will try to contact the devs and forward all this information so they hopefully can fix the bug. Until that happens we can't do anything about it.

**Comment by v0idp** [comment]
closing since AU bug not AUM
