### ISSUE TITLE
Hide from OBS Studio (aka. Docking Branch Multiple Viewports)

### ISSUE THREAD

**Issue by HAF1ZUR** [BitCrackers/AmongUsMenu#304]
Is this possible?  or even separate the AUM from the game itself

When streaming, menu is visible, even when do not record overlay is selected in OBS

This use to work, it may be an OBS issue, so apologies if it is

**Comment by v0idp** [comment]
depends. are you using the steam version with steam overlay activated ? then it should work since the menu hooks the steam overlay. maybe there was an option in OBS to disable recording steam overlay ? also make sure to start OBS after starting AUM.

We had talks about adding the docking branch of imgui which allows us to render on multiple viewports, which would allow you to move the menus outside the game window.

**Comment by HAF1ZUR** [comment]
I am using the EPIC version, i also have the steam version, will try that

**Comment by HAF1ZUR** [comment]
Ok, this works with STEAM, but with EPIC it does not

Moving the menus outside the game window would make it work on EPIC

**Comment by v0idp** [comment]
the menus outside the game window would work on every version yes.

**Comment by kotae4** [comment]
Just want to add EGS has their own overlay too, so maybe we could do with that whatever we're doing with the steam overlay?

**Comment by v0idp** [comment]
I dont even know what EGS is
