### ISSUE TITLE
why does this game have access to the clipboard api?

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [BitCrackers/AmongUsMenu#363]
thats kinda sus that this cheat can access the clipboard and seems to love tinkering with shell32.dll and more

care to explain this suspicious activity of your cheat are you gonna just block me like the little virus making pussy you (probably) are?

heres a link to the suspicious activity mentioned https://www.hybrid-analysis.com/sample/fcbd63e34ec67d1c446562272a0f4e03a236ffe8983e26c719cdddbe3fb9e5da/627dcd6832e6ba42d24dd253

**Comment by OsOmE1** [comment]
Pardon the language but who the fuck do you think you are coming here insulting us without anything concrete to base it off. If you actually had any technical know how you would know that anything downloaded from GitHub here is compiled on GitHub servers automatically straight from this repo. If you really want to know if there is a virus read the code otherwise I kindly advise you to keep your derogatory comments to yourself.

**Comment by v0idp** [comment]
I blocked him from the organization. It doesn't make any sense to argue with people like this @OsOmE1
