### ISSUE TITLE
currency

### ISSUE THREAD

**Issue by xAffan** [BitCrackers/AmongUsMenu#484]
make it possible to add beans and cosmusibcle points since you get that after finishing a game

**Comment by william1east** [comment]
You shouldn't need beans or cosmicube points because all cosmetics (including ones in cosmicubes) are unlocked automatically when you start aum and can be viewed by others, additionally, Beans are calculated server side, so you cant mess with them even if you wanted to, [this was found out by v0idp](https://i.imgur.com/d6OUFJA.png).
