### ISSUE TITLE
Have all cosmetics but the delete key doesnt open the menu

### ISSUE THREAD

**Issue by RizzlyBear1** [BitCrackers/AmongUsMenu#539]
It lets me use every cosmetic but the menu doesnt open when i press the delete key

**Comment by hs233666** [comment]
Not the menu's problem

**Comment by JakeHumter** [comment]
Easy step remove the setting file on your among us directory then restart your game then click delete then boom theres the menu!

**Comment by Kunal1320** [comment]
they is no setting.json file

**Comment by william1east** [comment]
Yes there isFrom: Kunal1320Sent: Thursday, July 6, 2023 2:15 AMTo: BitCrackers/AmongUsMenuCc: SubscribedSubject: Re: [BitCrackers/AmongUsMenu] Have all cosmetics but the delete key doesnt open the menu (Issue #539) they is no setting.json file—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Kunal1320** [comment]
Hmm I got One solution using Process Hacker and Injecting dll manually

**Comment by Kunal1320** [comment]
![image](https://github.com/BitCrackers/AmongUsMenu/assets/110390795/bf052421-0bd0-4772-9b24-55a464a713b9)
